###Get all books
GET http://localhost:8080/books

###Get Book by ID
GET http://localhost:8080/books/68cbd41fcad42dae933ed497

###Create New Book
POST http://localhost:8080/books
Content-Type: application/json

{
    "title": "The Little Prince",
    "author": "Maya Grace",
    "genre": "New Genre",
    "publishedYear": 2000,
    "available": true
    
}

###Protected routes below this line###
GET http://localhost:8080/profile
Accept: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImZGVDZqN3F3M2dVT3V6T2g1Nm9GSyJ9.eyJpc3MiOiJodHRwczovL2Rldi1nYndyc2kzdXBmc2ZjendwLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJodUlYMVo0d1c3N2tMWHY3eng4bUsybk02RUVGd0FORkBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9saWJyYXJ5LWFwaSIsImlhdCI6MTc1ODY1Mjg2MywiZXhwIjoxNzU4NzM5MjYzLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMiLCJhenAiOiJodUlYMVo0d1c3N2tMWHY3eng4bUsybk02RUVGd0FORiJ9.oeevoLObNKd4g6857mhCuh6VUQ9PmX_7ObX-2iPMBOPs05SXwigIuJPI9xkncO4wD-zeAy4dqJYjszv6keStzVJDvnKXvtIgMCZEUboaFLfVWxfOg-UG3e4FFYgu6LV9QzhGt8W26e-roPXy0U5zjgT8tBYXt9SAHzNfQYpJJUUewN1Zy3QjUmTuYYWNELtRkZJ2Akp3KXs-AsbKE94w3xdEnY5HeSnvyGtEd7CB6LypqW9eI8bNQ2saOzfEHWw9UohYo28NRJNBedEMcQWrLGPfW1oo5TyzdPDyhnWv6Vt9AYzRYs6SbCYrPAIDAq0BygJ278WTbJVvovcPURF5dw
###Update Book
PUT http://localhost:8080/books/68cbd41fcad42dae933ed497
Content-Type: application/json

{
    "title": "New Book Title",
    "author": "New Author Name",
    "genre": "New Genre",
    "publishedYear": 3050,
    "available": true
   
}

###Delete Book
DELETE http://localhost:8080/books/68cbd5bc4381f32efa8ad49b

###Get all users
GET http://localhost:8080/user

###Register User
POST http://localhost:8080/user
Content-Type: application/json

{
    "userName": "Bettina Menya",
    "email": "betina@anymail.com",
    "password":"000"
}

###Edit User
PUT http://localhost:8080/user/68cd17c8e44737cf1b5394fe
Content-Type: application/json

{
    "userName": "Bettina Menya",
    "email": "menya@gmail.com",
    "password":"0001"
}

###Delete User
DELETE http://localhost:8080/user/68cd17c8e44737cf1b5394fe

### Get access token
POST https://dev-gbwrsi3upfsfczwp.us.auth0.com/oauth/token
Content-Type: application/json

{
  "client_id": "S5dOFF3TPlpwrmij5VBYq0THGnBIrNgE",
  "client_secret": "obXuAbdd0bCLRPYBGs-LbvFeCAipYC5SoLOmx6cvMz7dpI9J_m1j5GIzMBd5j4SZ",
  "audience": "https://library-api",
  "grant_type": "client_credentials"
}

